name: Deploy to k3s

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Setup kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl config view  # Debugging: Check kubeconfig is correctly loaded
        kubectl cluster-info  # Debugging: Ensure the cluster is accessible

    - name: Deploy Nginx Application
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl apply -f hello-world.yaml
        kubectl get all -n default  # Debugging: List all resources after applying
        kubectl rollout status deployment/hello-world || kubectl describe deployment hello-world  # Debugging in case of failure
